---
- name: Clone DNSlivery github repository
  git:
    repo: https://github.com/no0be/DNSlivery.git
    dest: /home/ubuntu/DNSlivery/
    clone: yes
    update: yes
- name: Install python3-pip
  package:
    name: python3-pip
    state: present
- name: Install scapy
  pip:
    name: scapy==2.4.3
- name: Create directory for files to share
  file:
    path: /tmp/dns-delivery
    state: directory
- name: Create symbolic link
  file:
    src: "/usr/lib/x86_64-linux-gnu/libc.a"
    dest: "/usr/lib/x86_64-linux-gnu/liblibc.a"
    state: link
- name: Creating a file with content
  copy:
    dest: "/tmp/dns-delivery/test.txt"
    content: |
      Test DNS File Download
- name: Download Invoke-DNSExfiltrator.ps1
  get_url:
    url: https://raw.githubusercontent.com/Arno0x/DNSExfiltrator/master/Invoke-DNSExfiltrator.ps1
    dest: /tmp/dns-delivery/Invoke-DNSExfiltrator.ps1
- name: Clone DNSExfiltrator github repository
  git:
    repo: https://github.com/Arno0x/DNSExfiltrator.git
    dest: /home/ubuntu/DNSExfiltrator/
    clone: yes
    update: yes
- name: Install python2
  package:
    name: python2
    state: present
- name: Install python-pip
  package:
    name: python-pip
    state: present
- name: Install dnslib for Python 2.7
  pip:
    name: dnslib
    executable: pip2